### ISSUE TITLE
First Multi-selection is flashing

### ISSUE THREAD

**Issue by Iknuppe** [inffeldgroup/sw2016#3]
On the start site or if you return from the favorite activity the gridview will unintentionally update itself.

Auf der ersten Seite oder wenn man von Favorite wieder auf die MainActivity zurückkommt wird beim Longclick alle items in der Gridview aktualisiert.

**Comment by maxschuh** [comment]
not fixed yet

Steps to reproduce:
1. reopen the main activity
2. select a picture
3. selection is buggy

How it should be:
1. reopen the main activity
2. swipe right to get new pictures
3. selection works

**Comment by m-starke** [comment]
Still not fixed; will be considered in next service update!
